config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
	
  namespace :frontend , path: '/' do
    resources :critics, :themes
  end
  root 'views#index'
  get '/' , to: 'views#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backend.rb
module Backend
  def self.table_name_prefix
    'backend_'
  end
end

app/models/backend/opinion.rb
class Backend::Opinion < ApplicationRecord
end

app/models/frontend.rb
module Frontend
  def self.table_name_prefix
    'frontend_'
  end
end

app/models/frontend/critic.rb
class Frontend::Critic < ApplicationRecord
	belongs_to :theme 

	validates :title,presence: true
	validates :description,presence: true, length: {minimum: 20}
	validates :score,presence: true , :inclusion => 0..10
	validates :theme_id,presence: true
end

app/models/frontend/theme.rb
class Frontend::Theme < ApplicationRecord
	has_many :critics , class_name: "Frontend::Critic", through: :theme_id
	
	validates :name,presence: true
	#validates :name,presence: true,uniqueness: true
	validates :description,presence: true, length: {minimum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'app/application'

end

app/controllers/frontend/critics_controller.rb
class Frontend::CriticsController < ApplicationController
  before_action :set_frontend_critic, only: [:show, :edit, :update, :destroy]
  before_action :set_page_title

  # GET /frontend/critics
  # GET /frontend/critics.json
  def index
    @frontend_critics = Frontend::Critic.all
    
    
  end

  # GET /frontend/critics/1
  # GET /frontend/critics/1.json
  def show
  end

  # GET /frontend/critics/new
  def new
    @frontend_critic = Frontend::Critic.new
  end

  # GET /frontend/critics/1/edit
  def edit
  end

  # POST /frontend/critics
  # POST /frontend/critics.json
  def create
    @frontend_critic = Frontend::Critic.new(frontend_critic_params)

    respond_to do |format|
      if @frontend_critic.save
        format.html { redirect_to @frontend_critic, notice: 'Critic was successfully created.' }
        format.json { render :show, status: :created, location: @frontend_critic }
      else
        format.html { render :new }
        format.json { render json: @frontend_critic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frontend/critics/1
  # PATCH/PUT /frontend/critics/1.json
  def update
    respond_to do |format|
      if @frontend_critic.update(frontend_critic_params)
        format.html { redirect_to @frontend_critic, notice: 'Critic was successfully updated.' }
        format.json { render :show, status: :ok, location: @frontend_critic }
      else
        format.html { render :edit }
        format.json { render json: @frontend_critic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frontend/critics/1
  # DELETE /frontend/critics/1.json
  def destroy
    @frontend_critic.destroy
    respond_to do |format|
      format.html { redirect_to frontend_critics_url, notice: 'Critic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frontend_critic
      @frontend_critic = Frontend::Critic.find(params[:id])
    end
    def set_page_title
      @page_title = "Críticas"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frontend_critic_params
      params.require(:frontend_critic).permit(:score, :title, :description, :theme_id)
    end
end

app/controllers/frontend/themes_controller.rb
class Frontend::ThemesController < ApplicationController
  before_action :set_frontend_theme, only: [:show, :edit, :update, :destroy]
  before_action :set_page_title
  # GET /frontend/themes
  # GET /frontend/themes.json
  def index
    @frontend_themes = Frontend::Theme.all
  end

  # GET /frontend/themes/1
  # GET /frontend/themes/1.json
  def show
  end

  # GET /frontend/themes/new
  def new
    @frontend_theme = Frontend::Theme.new
  end

  # GET /frontend/themes/1/edit
  def edit
  end

  # POST /frontend/themes
  # POST /frontend/themes.json
  def create
    @frontend_theme = Frontend::Theme.new(frontend_theme_params)

    respond_to do |format|
      if @frontend_theme.save
        format.html { redirect_to @frontend_theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @frontend_theme }
      else
        format.html { render :new }
        format.json { render json: @frontend_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frontend/themes/1
  # PATCH/PUT /frontend/themes/1.json
  def update
    respond_to do |format|
      if @frontend_theme.update(frontend_theme_params)
        format.html { redirect_to @frontend_theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @frontend_theme }
      else
        format.html { render :edit }
        format.json { render json: @frontend_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frontend/themes/1
  # DELETE /frontend/themes/1.json
  def destroy
    @frontend_theme.destroy
    respond_to do |format|
      format.html { redirect_to frontend_themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frontend_theme
      @frontend_theme = Frontend::Theme.find(params[:id])
    end

    def set_page_title
      @page_title = "Temas"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frontend_theme_params
      params.require(:frontend_theme).permit(:name, :description)
    end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontend/critics_helper.rb
module Frontend::CriticsHelper
end

app/helpers/frontend/themes_helper.rb
module Frontend::ThemesHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/frontend/critics/_form.html.slim
= form_for @frontend_critic do |f|
  - if @frontend_critic.errors.any?
    div class="alert alert-danger alert-with-icon animated fadeInDown" data-notify="container"
      span data-notify="icon" class="mdi mdi-alert"
      span data-notify="message" class="text-justify"
        - @frontend_critic.errors.full_messages.each do |message|
          li #{message}  
  .row
    .form-group.col-12
      .col-3
        = f.label :score do
          span Puntuación
      .col-8        
        = f.number_field :score , class:"form-control"
    .form-group.col-12
      .col-3  
        = f.label :title do
          span Titulo
      .col-8  
        = f.text_field :title  , class:"form-control"
    .form-group.col-12
      .col-3  
        = f.label :description do
          span Descripción
      .col-8  
        = f.text_area :description , class:"form-control"
    .form-group.col-12
      .col-3  
        = f.label :theme_id do    
          span Tema
      .col-8  
        = f.collection_select(:theme_id, Frontend::Theme.all, :id, :name,{:include_blank => 'Escoge un tema...'}, html_options = {:class => "custom-select"} )
    
    .col-12.row
      a.btn.btn-danger.pull-left href="#{frontend_critics_path}"
        | Volver
      .actions = f.submit "Guardar",class:"btn btn-primary"

app/views/frontend/critics/edit.html.slim
.row
  .col-12
    .card
      .card-header
        .row
          h2.card-title.px-3 Editar #{@page_title}
          nav.px-3  aria-label="breadcrumb"
            ol class="breadcrumb"
              li class="breadcrumb-item"
                a href="#{root_path}" 
                  | Inicio
              li class="breadcrumb-item"
                a href="#{frontend_critics_path}"
                  | Críticas
              li class="breadcrumb-item active" aria-current="page"
                | Editar 
                = @frontend_critic.title
      .card-body
        .row
          .col-12
            == render 'form'
          
          .col-12
          	br

app/views/frontend/critics/index.html.slim
.card
  .card-title.text-center
    h1 = @page_title
    .row.text-center.ml-5
      nav.px-3.col-6  aria-label="breadcrumb"
        ol class="breadcrumb"
          li class="breadcrumb-item"
            a href="#{root_path}" 
              | Inicio
          li class="breadcrumb-item"
            = @page_title   
      .col-5
        = link_to 'Nueva Criticas', new_frontend_critic_path ,class:"btn btn-dark mb-4 animated infinite pulse delay-5s"
  .card-body
    a
    .col-12
      - @frontend_critics.each do |frontend_critic|
        .col-md-5.critic
          .critic-title 
            .row           
              strong.h2.col-7 = frontend_critic.title     
              .col-3
                = link_to "Ver mas ",frontend_critic,class:"btn btn-success"       
          .critic-subtitle.col-8
            strong.h4 = Frontend::Theme.find(frontend_critic.theme_id).name             
          .critic-body              
            p = frontend_critic.description
            p.h4 #{frontend_critic.score}/10 
            /lo de arriba es una interpolación
 

app/views/frontend/critics/new.html.slim
.row
  .col-12
    .card
      .card-header
        .row
          h2.card-title.px-3 Crear #{@page_title}
          nav.px-3  aria-label="breadcrumb"
            ol class="breadcrumb"
              li class="breadcrumb-item"
                a href="#{root_path}" 
                  | Inicio
              li class="breadcrumb-item"
                a href="#{frontend_critics_path}"
                  | Críticas
              li class="breadcrumb-item active" aria-current="page"
                | Crear #{@page_title}
      .card-body
        .row
          .col-12
            == render 'form'
          
          .col-12
          	br

app/views/frontend/critics/show.html.slim
.row
  .col-12
    .card
      .card-header
        .row
          h2.card-title.px-3 #{@page_title}
          nav.px-3  aria-label="breadcrumb"
            ol class="breadcrumb"
              li class="breadcrumb-item"
                a href="#{root_path}" 
                  | Inicio
              li class="breadcrumb-item"
                a href="#{frontend_critics_path}"
                  | #{@page_title}
              li class="breadcrumb-item active" aria-current="page"
                = @frontend_critic.title
      .card-body
        .row
          .col-12.col-sm-6.d-inline-flex.flex-row 
            .h4
              strong Tema: 
            .bg-light.rounded.h4.px-4
              = Frontend::Theme.find(@frontend_critic.theme_id).name                       
          .col-12.col-sm-6.d-inline-flex.flex-row             
            .h4
              strong Titulo:  
            .bg-light.rounded.h4.px-4
              = @frontend_critic.title
          .col-12.col-sm-6.d-inline-flex.flex-row 
            .h4
              strong Descripción:
            .bg-light.rounded.h4.px-4
              = @frontend_critic.description
          .col-12.col-sm-6.d-inline-flex.flex-row 
            .h4
              strong Puntuación:
            .bg-light.rounded.h4.px-4
              = @frontend_critic.score   
              | /10           
          
        .row
          .col-12.col-sm-6.text-center 
          
            = link_to 'Editar', edit_frontend_critic_path(@frontend_critic), class:"btn btn-warning"
            
            = link_to 'Volver', frontend_critics_path ,class:"btn btn-primary"

app/views/frontend/themes/_form.html.slim
= form_for @frontend_theme do |f|
  - if @frontend_theme.errors.any?
    div class="alert alert-danger alert-with-icon animated fadeInDown" data-notify="container"
      span data-notify="icon" class="mdi mdi-alert"
      span data-notify="message" class="text-justify"
        - @frontend_theme.errors.full_messages.each do |message|
          li #{message}  
  .row
    .form-group.col-12
      .col-3
        = f.label :name do
          span Nombre
      .col-8        
        = f.text_field :name , class:"form-control"
  .row
    .form-group.col-12
      .col-3
        = f.label :description do
          span Decripción
      .col-8        
        = f.text_area :description , class:"form-control"

  .col-12
    a.btn.btn-danger.pull-left href="#{frontend_themes_path}"
      | Volver     
    = f.submit "Guardar ",class:"btn btn-secondary" ,id:"submit_changes"

app/views/frontend/themes/edit.html.slim
.row
  .col-12
    .card
      .card-header
        .row.px-4
          h4.card-title Editar #{@page_title}
          nav.px-3.col-6  aria-label="breadcrumb"
            ol class="breadcrumb"
              li class="breadcrumb-item"
                a href="#{root_path}" 
                  | Inicio
              li class="breadcrumb-item"
                a href="#{frontend_themes_path}" 
                  | Temas
              li class="breadcrumb-item"
                | Editar 
                = @frontend_theme.name  
      .card-body
        .row
          .col-12
            == render 'form'
          
          .col-12
          	br

app/views/frontend/themes/index.html.slim
.card
  .card-title.text-center
    h1 Temas Para Criticar
    .row.text-center.ml-5
      nav.px-3.col-6  aria-label="breadcrumb"
        ol class="breadcrumb"
          li class="breadcrumb-item"
            a href="#{root_path}" 
              | Inicio
          li class="breadcrumb-item"
            | Temas
      .col-5
        = link_to 'Nuevo Tema', new_frontend_theme_path ,class:"btn btn-dark mb-4 animated infinite pulse delay-5s", id:"new_theme"
  .card-body

    .col-12
      - @frontend_themes.each do |frontend_theme|
        .col-md-5.theme.border.rounded
          
          .theme-title.rounded
            strong.h2 = frontend_theme.name
            = link_to "Ver mas ",frontend_theme,class:"btn btn-primary"
          .theme-body
            p =frontend_theme.description

app/views/frontend/themes/new.html.slim
.row
  .col-12
    .card
      .card-header
        .row.px-4
          h4.card-title Crear #{@page_title}
          nav.px-3.col-6  aria-label="breadcrumb"
            ol class="breadcrumb"
              li class="breadcrumb-item"
                a href="#{root_path}" 
                  | Inicio
              li class="breadcrumb-item"
                a href="#{frontend_themes_path}" 
                  | Temas
              li class="breadcrumb-item"
                | Crear #{@page_title}              
      .card-body
        .row
          .col-12
            == render 'form'
          
          .col-12
          	br

app/views/frontend/themes/show.html.slim
.row
  .col-12
    .card
      .card-header
        .row
          h2.card-title.px-3 #{@page_title}
          nav.px-3  aria-label="breadcrumb"
            ol class="breadcrumb"
              li class="breadcrumb-item"
                a href="#{root_path}" 
                  | Inicio
              li class="breadcrumb-item"
                a href="#{frontend_themes_path}"
                  | #{@page_title}
              li class="breadcrumb-item active" aria-current="page"
                = @frontend_theme.name

      .card-body
        .row
          .col-12.col-sm-6.d-inline-flex.flex-row             
            .h3
              strong Nombre:  
            .bg-light.rounded.h3.px-4
              = @frontend_theme.name
          .col-12.col-sm-6.d-inline-flex.flex-row 
            .h3
              strong Descripción:
            .bg-light.rounded.h3.px-4
              = @frontend_theme.description
        .row
          .col-12.col-sm-6.text-center 
          
            = link_to 'Editar', edit_frontend_theme_path(@frontend_theme), class:"btn btn-warning", id:"edit_theme"
            
            = link_to 'Volver', frontend_themes_path ,class:"btn btn-primary"

app/views/layouts/app/application.html.slim
doctype html
html
  head
    title Opinion  
    = csrf_meta_tags
    = csp_meta_tag
    
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    link rel="shortcut icon" type="image/png" href=image_url("icon.png")
    /link href="url()" rel="stylesheet"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
  body style="background-image: url(#{asset_path 'bg.jpg'});"
    
    == render partial: 'layouts/app/partials/navbar'
    .container
      == render partial: 'layouts/app/partials/header'

      == yield
    
    == render partial: 'layouts/app/partials/footer'  

     
  
  javascript:
    

  
  ==yield :scripts

app/views/layouts/app/partials/_footer.html.slim
.col-12.footer 
	.row
		.col-4
			p Información de Contacto
		.col-4
			p Información de Contacto			
		.col-4
			p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur minus sit libero laboriosam odio 		

app/views/layouts/app/partials/_header.html.slim
.display-1 Tu opinion .com

app/views/layouts/app/partials/_navbar.html.slim
.nav__menu
	Slide.nav-bar id="slide_burguer" message="login"
/#sidebar

.modal.fade id="login-modal"
	.modal-dialog role="document"
	  .modal-content
	  	.modal-header
		    .modal-title.text-center
					-if user_signed_in?
						.h4 Bienvenido
					-else 
						.row
							.h4.px-2 Iniciar Sesión
							= link_to "Nuevo Usuario",new_user_registration_path,class:"btn btn-primary" 
	    .modal-body
	    	- if user_signed_in?
					.h5 Hola #{current_user.email}	    		
					.col-12.form-group.text-center
						= link_to("Cerrar Sesión", destroy_user_session_path, :method => 'delete' , class:'btn btn-danger',id:"log_out" ) 
						button type="button" id="close_modal" class="btn btn-secondary" data-dismiss="modal" aria-label="Close"	
								| Cerrar     						        
    		-else
		    	= form_for(:user, :url => session_path(:user)) do |f|
						- if flash[:alert]
							div class="alert alert-danger alert-with-icon" data-notify="container"
								span data-notify="icon" class="mdi mdi-alert"
								span data-notify="message" class="text-justify" #{flash[:alert]}

						- if flash[:notice]
							div class="alert alert-info alert-with-icon" data-notify="container"
								span data-notify="icon" class="mdi mdi-information-outline"
								span data-notify="message" class="text-justify" #{flash[:notice]}

						.input-group.mb-3
							.input-group-prepend
								= f.label :email do
									span.input-group-text id="email_login" 
										| Correo Eletrónico					  	
							= f.email_field :email  ,  :class => 'form-control' , placeholder:'Correo Eletrónico' , 'aria-label':"email_login"	, 'aria-describedby':'email_login'				  
						.input-group.mb-3
							.input-group-prepend
								= f.label :password do
									span.input-group-text id="password_login" 
										| Contraseña					  	
							= f.password_field :password  ,  :class => 'form-control' , placeholder:'Contraseña' , 'aria-label':"password_login"	, 'aria-describedby':'password_login'				  	
						.input-group.mb-3
							.input-group-prepend
								.form-control
									.input-group-text.fill__all
										= f.check_box :remember_me  , class:''							  				  
							= f.label :remember_me do
								span.form-control id="password_login" 
									| Recuerdame					  	

						.col-12.form-group.text-center
							= f.submit 'Iniciar Sesion', class:'btn btn-primary' 
							button type="button" id="close_modal" class="btn btn-secondary" data-dismiss="modal" aria-label="Close"	
								| Cerrar         

						.col-12.form-group.text-center
							= link_to "Forgot your password?", new_password_path(:user) 

		  		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectInterface</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/views/index.html.slim
.card
	.card-title
		p.h2.text-center Lo que tu pienses Importa
	.carousel.slide#carousel data-ride="carousel" 
		.carousel-inner style="width: 100%; height: 600px;"
			.carousel-item.active.main-carousel style="background-image: url(#{asset_path 'books.jpg'});"

			.carousel-item.main-carousel style="background-image: url(#{asset_path 'food.jpg'});"

			.carousel-item.main-carousel style="background-image: url(#{asset_path 'movie-1.jpg'});"

			.carousel-item.main-carousel style="background-image: url(#{asset_path 'restaurant.jpg'}); "
			
		a.carousel-control-prev href="#carousel" role="button" data-slide="prev"
	    span.carousel-control-prev-icon aria-hidden="true"
	    span.sr-only Anterior
		a.carousel-control-next href="#carousel" role="button" data-slide="next"
	    span.carousel-control-next-icon aria-hidden="true"
	    span.sr-only Siguiente
  	